proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  specs:
    - id: jupyter-notebook-lab
      display-name: Jupyter Notebook Lab
      description: Jupyter Notebook running in lab mode.
      container-cmd: ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.base_url=#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"]
      container-image: openanalytics/shinyproxy-jupyter-datascience
      container-volumes: [ "/tmp/jupyter/#{proxy.userId}/work:/home/jovyan/work"]
      port: 8888
      websocket-reconnection-mode: None
      target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
logging:
  file:
    name: shinyproxy.log
